language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops-pipelinetest
  api_key:
    secure: QipcU+7jniaJXPMH86L2xk3hi1q+gB4sp7vgGXxce6oj3VW5E3kL7+vLQhyw4LqUCpEnxwMAdSpdWz3PEms1lk2ucF9BQadfLqKxV2654SWHX2lQAiYmEAH4lxIFa0Up6/57CCDM+vttBd3ARIHp+jMgmOwpfoIR4CiZBxZTRkFWdIJHtJBhDodn27NBrzbn97POVmiY1ZY+1x/xkQEr2ug/5uLGyt9KBczaZo9/0Y44qTop37tSafSdT7rLtuBSmAhAvIE8gdUS0tkijPuut9KuJKL/Hm1Fo4mvR2Xxgq6myPfFtx+g5jt3KkWqx3apiGq0oHRfBUooOP8fCe2mzjPom/Xvg4myhQWUgvFe4RjQERQDWrQmFvBHUmswCW1GfXVPoa/e8kjEtG1tYVVoWMdLPYIHTXuvHEOagcVvnapM07Vsqse5QZFRjvT1NI33O2i0Qyin+zgRk+trtGCbKLjWTS349D1Zd/7K2tIfKWoNiY1uo5ptcomGw/FTosQVaDopVPM3z/zcFwAxi1926A5hrr/w3d3NwoaDe9wIiv19WlreN1NFJPhej1j+ylW9Q5V4mc0ULFscRGhWCwSCsN4eATR4/ESjvDr/OcjutKWh8QHt9pKGX5sXRw3IxHvCDASSdGTZEsa4BG60+TFafku8WOxeMValhSEqO2/9Bz8=
